name: Model Deployment Automation

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      action_type:
        description: 'Action to perform'
        required: true
        default: 'register'
        type: choice
        options:
          - register
          - update

env:
  MODEL_API_URL: "https://backoffice.dev.api.discomax.com/mlp-metadata-manager/meta-manager"

jobs:
  deploy-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Determine action type
        id: action
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "action_type=${{ github.event.inputs.action_type }}" >> $GITHUB_OUTPUT
          else
            echo "action_type=register" >> $GITHUB_OUTPUT
          fi

      - name: Register Model
        if: ${{ steps.action.outputs.action_type == 'register' }}
        run: |
          cat << 'EOF' > register_model.py
          import json, requests, os, sys, time

          def register_model():
              api_url = os.environ.get("MODEL_API_URL")
              if not api_url:
                  print("Missing MODEL_API_URL")
                  sys.exit(1)

              headers = {"Content-Type": "application/json"}

              config = {
                  "model_name": "mlt-batch",
                  "variant": "sllim-tg-pkg-300-gh-" + str(int(time.time())),
                  "owner_team": "personalization",
                  "omd_business_service": "content-discovery",
                  "related_features": {},
                  "inference_configuration": {"response_item_limit": -1},
                  "serving_configuration": {
                      "autoscaling": True,
                      "autoscale_conditions": {"rps": 20},
                      "min_instance": 1,
                      "max_instance": 5,
                      "machine_type": "ml.c5.xlarge",
                      "processor": "cpu",
                      "framework": {"framework_name": "tensorflow", "framework_version": "2.9.2"},
                      "shadow_config": {}
                  },
                  "serving_regions": ["us-east-1"]
              }

              register_url = f"{api_url}/v1/models/register"
              print(f"Registering {config['model_name']} variant {config['variant']}")
              print(f"API URL: {register_url}")
              print(f"Payload: {json.dumps(config, indent=2)}")

              try:
                  response = requests.post(register_url, json=config, headers=headers)
                  print(f"Status: {response.status_code}")
                  print(f"Body: {response.text}")

                  if response.status_code in [200, 201]:
                      print("Model registered successfully!")
                  elif response.status_code == 400 and "already exists" in response.text:
                      print("Model already exists, continuing...")
                  else:
                      print("Failed to register model")
                      sys.exit(1)
              except requests.exceptions.RequestException as e:
                  print(f"Request failed: {e}")
                  sys.exit(1)

          if __name__ == "__main__":
              register_model()
          EOF
          python register_model.py

      - name: Update Model
        if: ${{ steps.action.outputs.action_type == 'update' }}
        run: |
          cat << 'EOF' > update_model.py
          import json, requests, os, sys

          def update_model():
              api_url = os.environ.get("MODEL_API_URL")
              if not api_url:
                  print("Missing MODEL_API_URL")
                  sys.exit(1)

              headers = {"Content-Type": "application/json"}

              model_id = "CD:personalization:mlt-batch:sllim-tg-pkg-3"  # hardcoded
              update_url = f"{api_url}/v1/models/update/{model_id}"

              payload = {
                  "model": {
                      "serving_configuration": {
                          "autoscaling": True,
                          "autoscale_conditions": {"rps": 10},
                          "min_instance": 1,
                          "max_instance": 30,
                          "machine_type": "ml.c5.xlarge",
                          "processor": "cpu",
                          "framework": {"framework_name": "tensorflow", "framework_version": "2.9.2"},
                          "shadow_config": {}
                      }
                  }
              }

              print(f"Updating {model_id}")
              print(f"API URL: {update_url}")
              print(f"Payload: {json.dumps(payload, indent=2)}")

              try:
                  response = requests.put(update_url, json=payload, headers=headers)
                  print(f"Status: {response.status_code}")
                  print(f"Body: {response.text}")

                  if response.status_code not in [200, 201]:
                      print("Failed to update model")
                      sys.exit(1)
              except requests.exceptions.RequestException as e:
                  print(f"Request failed: {e}")
                  sys.exit(1)

          if __name__ == "__main__":
              update_model()
          EOF
          python update_model.py

      - name: Summary
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Model deployment completed successfully!"
            echo "Action: ${{ steps.action.outputs.action_type }}"
          else
            echo "Model deployment failed"
          fi
